-- Delete data from tables with foreign key references first
DELETE FROM EQ_CMONITORIZACAO;
DELETE FROM INSPECAO_PRINCIPAL;
DELETE FROM INSPECAO_EXPEDITA;
DELETE FROM DOCUMENTO;
DELETE FROM CAMPANHA_MONITORIZACAO;
DELETE FROM TRABALHO;
DELETE FROM EQUIPAMENTO;

-- Delete data from tables referenced by foreign keys
DELETE FROM SOLUCAO_ESTRUTURAL;
DELETE FROM OBRA_CONTENCAO;

-- Delete data from remaining tables
DELETE FROM UTILIZADOR;
DELETE FROM TIPO_ESTRUTURA;
