-- remove views
DROP VIEW IF EXISTS public.informacoes_obras;
DROP VIEW IF EXISTS public.trabalhos_ano_passado;

-- remove table by order
DROP TABLE IF EXISTS SOLUCAO_ESTRUTURAL;
DROP TABLE IF EXISTS INSPECAO_PRINCIPAL;
DROP TABLE IF EXISTS INSPECAO_EXPEDITA;
DROP TABLE IF EXISTS EQ_CMONITORIZACAO;
DROP TABLE IF EXISTS EQUIPAMENTO;
DROP TABLE IF EXISTS DOCUMENTO;
DROP TABLE IF EXISTS CAMPANHA_MONITORIZACAO;
DROP TABLE IF EXISTS TRABALHO;
DROP TABLE IF EXISTS OBRA_CONTENCAO;
DROP TABLE IF EXISTS TIPO_ESTRUTURA;
DROP TABLE IF EXISTS UTILIZADOR;
